layout_spectrum: 0.46293857565998
typography_spectrum: 0.12866292833839313
color:
  brandStrength: 0.4612190816485978
  lightness: 0.028370642054660042
  saturation: 0.07899292231482076
  rhythmicContrast: 0.2970895478014124
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
opengraph:
  type: 'https://www.facebook.com/Jibes-beach-Club-130654326982359/'
  appId: Jibe's Beach Club
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f63df57-40ca-4f6d-a7a6-56ab9c33f11d.jpg
analytics:
  google: UA-59745346-2
author:
  email: info@jibesbeachclub.com
  url: ''
  name: Jibe's Beach Club
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ffa0f692-43de-4312-982a-166324e09580.jpg
name: Jibes Beach Club
navigation:
  - name: The Original Water-sports center in Vietnam
    url: 'http://www.jibesbeachclub.com/'
    type: external
  - name: 18th Vietnam Fun Cup coming in Feb 2017
    url: 'https://www.youtube.com/watch?v=av_VkYLsDWw'
    type: external
  - name: 'Full Moon Beach, one of the first resort on the bay'
    url: 'http://fullmoonbeach.com.vn/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed9b98d7-d15c-4413-b7e9-3b2ea314d477.jpg
title: where the wind blows
content: []
description: since 2000
purpose:
  - type: external
    url: 'http://www.jibesbeachclub.com'
    label: www.jibesbeachclub.com
  - type: contact
    url: 'mailto:info@jibesbeachclub.com'
    label: Contact us
